// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"nunu/backend/api/v1"
	"nunu/backend/init/gorm"
	"nunu/backend/persistence/jinzhu"
	"nunu/backend/service"
)

// Injectors from wire_injectors.go:

func CreateAdminApi() *v1.AdminApi {
	db := gorm.GetGormDB()
	iUserManageRepo := jinzhu.NewUserManageRepo(db)
	iAdminService := service.NewAdminService(iUserManageRepo)
	adminApi := v1.NewAdminApi(iAdminService)
	return adminApi
}

// wire_injectors.go:

var allProviders = wire.NewSet(jinzhu.Set, v1.Set, service.Set, gorm.GetGormDB)
